### ISSUE TITLE
R version

### ISSUE THREAD

**Issue by crancran2** [m-clark/mixedup#18]
I'm unable to install this package and get this error message: "package ‘mixedup’ is not available for this version of R." package may need updates.

**Comment by SchmidtPaul** [comment]
Maybe you need to update R, because the recommended installing method just worked for me:
```
remotes::install_github('m-clark/mixedup')
```
I have R version 4.0.3

**Comment by m-clark** [comment]
It depends on at least [R 3.6](https://github.com/m-clark/mixedup/blob/master/DESCRIPTION). But let me know if you still have issues.

```
remotes::install_github('m-clark/mixedup')

# if you don't already have rstanarm and/or brms

withr::with_envvar(c(R_REMOTES_NO_ERRORS_FROM_WARNINGS = "true"), 
  remotes::install_github('m-clark/mixedup')
)
```

**Comment by m-clark** [comment]
Going ahead and closing until something comes up.
