### ISSUE TITLE
**Summarise_model** returns *'Error: Can't transform a data frame with duplicate names.'*

### ISSUE THREAD

**Issue by russell-ligon** [m-clark/mixedup#19]
I am running into an issue when I call '**summarise_model'** on a mixed model object (class = "lmerModLmerTest"). The error returned is: "Error: Can't transform a data frame with duplicate names."

FWIW, @m-clark has worked with a dummy dataset I sent to him and found *NO* errors (suggesting, perhaps some versioning issue). That said, we are both running the same versions of 'dplyr', 'lme4', and 'mixedup' (1.0.2, 1.1.26, 0.3.8 respectively). My R version is 3.6.3 (and his is 4.0.3). Will update my R and see what happens...

`head(dfs2)`
Growth Days StartingValue      V4
1    0.0            1.2133686     0.4694595 XZ92877
2    1.2            0.5078494     0.4694595 XZ92877
3    0.5            0.7492574     0.4694595 XZ92877
4    1.5            0.5078494     0.3097708 TR59858
5    1.7            0.7492574     0.3097708 TR59858
6    0.0            1.2133686     0.3097708 TR59858

`lmer_fit2 <- lmer(Growth ~ Days*StartingValue + (1|V4), data = dfs2)`
`summarise_model(lmer_fit2,ci=FALSE)`
Error: Can't transform a data frame with duplicate names.
Run `rlang::last_error()` to see where the error occurred.

**Comment by russell-ligon** [comment]
"MASKING" was the problem --- I was running *lmer* and had also loaded the package **lmerTest**!

When I ran the model using **lme4::lmer** the error went away. Hope this helps somebody else!

**Comment by m-clark** [comment]
Thanks for opening and continuing to look into this!  This is good to know.  Maybe I can add a check/warning or in the documentation somewhere.

**Comment by m-clark** [comment]
@russell-ligon It should error now with a message to rerun the model with `lme4::lmer`.  The primary problem seemed to be with `extract_fixed_effects`, so at least some other functions still would work with an `lmerModLmerTest` object, just not any that would use `extract_fixed_effects`.  I could potentially work around it so it'd work with those objects, but that may not be any time soon.
