### ISSUE TITLE
Suppress "fixed-effect model matrix is rank deficient so dropping X columns / coefficients"

### ISSUE THREAD

**Issue by SchmidtPaul** [m-clark/mixedup#33]
Hi!
I would like to suppress the *"fixed-effect model matrix is rank deficient so dropping 1 columns / coefficients"* note, but neither `suppressMessages()` nor `suppressWarnings()` will do the job. Oh yeah and `verbose = FALSE` is also not affecting this. I guess [this line](https://github.com/covaruber/sommer/blob/af358ed5a4e8886dda5ccf7ad026f1187e47bee0/R/mmer.R#L306) could be made an actual warning or if left a `cat(...)`, it could be wrapped in another if-clause adding another argument to silence it?

**Comment by SchmidtPaul** [comment]
So sorry, wrong tab - wrong package. Please delete

**Comment by m-clark** [comment]
No worries! Can never have too many tabs open!
